// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOqFUtPVMStSjHLzlNYyKHYkBWMCK_xGc',
    appId: '1:281514621422:web:7466dd8bd604153817b6ff',
    messagingSenderId: '281514621422',
    projectId: 'lomi-learning',
    authDomain: 'lomi-learning.firebaseapp.com',
    storageBucket: 'lomi-learning.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwdl3Rl26dx8Lr_Xp-uYIdDr2aAPGXE2o',
    appId: '1:281514621422:android:10c5e622a81997b417b6ff',
    messagingSenderId: '281514621422',
    projectId: 'lomi-learning',
    storageBucket: 'lomi-learning.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2IGZvea3hFAJooozwKEB5nTcGYHs2TUg',
    appId: '1:281514621422:ios:a65b530ee15483a617b6ff',
    messagingSenderId: '281514621422',
    projectId: 'lomi-learning',
    storageBucket: 'lomi-learning.firebasestorage.app',
    iosBundleId: 'com.rally.lomiLearning',
  );
}
